# -*- coding: utf-8 -*-
"""DVDProjectver4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZDLdSUzDUCq7wLErZLfMT2QH1r-Jiro

#**E-COMMERCE DATA ANALYSIS**

###1. IMPORT LIBRARIES AND CONFIGURATION
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

sns.set_theme(style="whitegrid")

DATA_PATH = "/content"
OUTPUT_PATH = "/content/analysis_output"

Path(OUTPUT_PATH).mkdir(exist_ok=True)

print("Libraries imported successfully.")

"""###2. FILE PATHS"""

customers_file = f"{DATA_PATH}/customers_dataset.csv"
orders_file = f"{DATA_PATH}/orders_dataset.csv"
order_items_file = f"{DATA_PATH}/order_items_dataset.csv"
payments_file = f"{DATA_PATH}/order_payments_dataset.csv"
reviews_file = f"{DATA_PATH}/order_reviews_dataset.csv"
products_file = f"{DATA_PATH}/products_dataset.csv"
category_file = f"{DATA_PATH}/product_category_name_translation.csv"
sellers_file = f"{DATA_PATH}/sellers_dataset.csv"
geolocation_file = f"{DATA_PATH}/geolocation_dataset.csv"

mql_file = f"{DATA_PATH}/marketing_qualified_leads_dataset.csv"
closed_deals_file = f"{DATA_PATH}/closed_deals_dataset.csv"

print("File paths configured.")

"""###3. LOAD DATA"""

customers = pd.read_csv(customers_file)
orders = pd.read_csv(orders_file)
order_items = pd.read_csv(order_items_file)
payments = pd.read_csv(payments_file)
reviews = pd.read_csv(reviews_file)
products = pd.read_csv(products_file)
category_translation = pd.read_csv(category_file)
sellers = pd.read_csv(sellers_file)
geolocation = pd.read_csv(geolocation_file)

mql = pd.read_csv(mql_file)
closed_deals = pd.read_csv(closed_deals_file)

datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "category_translation": category_translation,
    "sellers": sellers,
    "geolocation": geolocation,
    "marketing_qualified_leads": mql,
    "closed_deals": closed_deals
}

print("All datasets loaded successfully.")

"""###4. DATASET INFORMATION & DUPLICATES"""

print("=" * 80)
print("DATASET INFORMATION")
print("=" * 80)

for name, df in datasets.items():

    print("\n" + "-" * 70)
    print(name.upper())
    print("-" * 70)

    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Columns:", df.columns.tolist())


print("\n")
print("=" * 80)
print("DUPLICATE CHECK")
print("=" * 80)

for name, df in datasets.items():

    print(
        f"{name}: {df.duplicated().sum()} duplicate rows"
    )

"""###5. REMOVE DUPLICATES"""

geolocation = geolocation.drop_duplicates()

print("Remaining rows:", len(geolocation))
print("Duplicate rows:", geolocation.duplicated().sum())

"""###6. DATA CONVERSION & HANDLING MISSING VALUES"""

# Convert order dates
order_date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in order_date_columns:

    if col in orders.columns:

        orders[col] = pd.to_datetime(
            orders[col],
            errors="coerce"
        )
# Convert review dates
review_date_columns = [
    "review_creation_date",
    "review_answer_timestamp"
]

for col in review_date_columns:

    if col in reviews.columns:

        reviews[col] = pd.to_datetime(
            reviews[col],
            errors="coerce"
        )

# Marketing dates
if "first_contact_date" in mql.columns:

    mql["first_contact_date"] = pd.to_datetime(
        mql["first_contact_date"],
        errors="coerce"
    )


if "won_date" in closed_deals.columns:

    closed_deals["won_date"] = pd.to_datetime(
        closed_deals["won_date"],
        errors="coerce"
    )

# Clean reviews
if "review_comment_title" in reviews.columns:

    reviews["review_comment_title"] = (
        reviews["review_comment_title"]
        .fillna("")
    )


if "review_comment_message" in reviews.columns:

    reviews["review_comment_message"] = (
        reviews["review_comment_message"]
        .fillna("")
    )


reviews["is_negative_review"] = (
    reviews["review_score"] <= 2
).astype(int)


reviews["is_one_star"] = (
    reviews["review_score"] == 1
).astype(int)

# Clean products
if "product_category_name" in products.columns:

    products["product_category_name"] = (
        products["product_category_name"]
        .fillna("unknown")
    )


dimension_columns = [
    "product_weight_g",
    "product_height_cm",
    "product_length_cm",
    "product_width_cm"
]

for col in dimension_columns:

    if col in products.columns:

        products[col] = products[col].fillna(
            products[col].median()
        )

# Category translation
if (
    "product_category_name" in products.columns
    and "product_category_name" in category_translation.columns
):

    products = products.merge(
        category_translation,
        on="product_category_name",
        how="left"
    )

    if "product_category_name_english" in products.columns:

        products["product_category_name_english"] = (
            products["product_category_name_english"]
            .fillna("unknown")
        )

# Marketing data
if "origin" in mql.columns:

    mql["origin"] = (
        mql["origin"]
        .fillna("Unknown")
    )

# Closed deals
closed_deal_categorical = [
    "business_type",
    "lead_type",
    "business_segment",
    "lead_behaviour_profile"
]

for col in closed_deal_categorical:

    if col in closed_deals.columns:

        closed_deals[col] = (
            closed_deals[col]
            .fillna("Unknown")
        )

# Geolocation
if "geolocation_state" in geolocation.columns:

    geolocation = geolocation.dropna(
        subset=["geolocation_state"]
    )


print("Cleaning completed.")

"""###7. ORDER STATUS AND DELIVERY ANALYSIS"""

print("=" * 80)
print("ORDER STATUS")
print("=" * 80)

print(orders["order_status"].value_counts())

print("\nOrder status percentage:")

print(
    orders["order_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# Delivered orders
delivered_orders = orders[
    orders["order_status"] == "delivered"
].copy()


delivered_orders = delivered_orders.dropna(
    subset=[
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
)

# Delivery metrics
delivered_orders["seller_handling_days"] = (
    delivered_orders["order_delivered_carrier_date"]
    - delivered_orders["order_purchase_timestamp"]
).dt.total_seconds() / 86400


delivered_orders["shipping_days"] = (
    delivered_orders["order_delivered_customer_date"]
    - delivered_orders["order_delivered_carrier_date"]
).dt.total_seconds() / 86400


delivered_orders["delivery_days"] = (
    delivered_orders["order_delivered_customer_date"]
    - delivered_orders["order_purchase_timestamp"]
).dt.total_seconds() / 86400


delivered_orders["estimated_delivery_days"] = (
    delivered_orders["order_estimated_delivery_date"]
    - delivered_orders["order_purchase_timestamp"]
).dt.total_seconds() / 86400


delivered_orders["delivery_delay_days"] = (
    delivered_orders["order_delivered_customer_date"]
    - delivered_orders["order_estimated_delivery_date"]
).dt.total_seconds() / 86400


# Late delivery flag
delivered_orders["is_late"] = (
    delivered_orders["delivery_delay_days"] > 0
).astype(int)

# Delivery category
def delivery_category(days):

    if days <= 0:
        return "On Time"

    elif days <= 3:
        return "1-3 Days Late"

    elif days <= 7:
        return "4-7 Days Late"

    else:
        return "More than 7 Days Late"


delivered_orders["delivery_performance"] = (
    delivered_orders["delivery_delay_days"]
    .apply(delivery_category)
)

# Remove invalid delivery values
delivered_orders = delivered_orders[
    delivered_orders["delivery_days"] >= 0
].copy()


print("\n")
print("=" * 80)
print("DELIVERY SUMMARY")
print("=" * 80)

print(
    delivered_orders[
        [
            "seller_handling_days",
            "shipping_days",
            "delivery_days",
            "delivery_delay_days"
        ]
    ].describe()
)


late_rate = (
    delivered_orders["is_late"].mean() * 100
)

print(f"\nLate delivery rate: {late_rate:.2f}%")

"""###8. CREATE ORDER-LEVEL ANALYTICAL DATASET"""

# Order item summary
order_item_summary = (
    order_items
    .groupby("order_id")
    .agg(
        item_count=("order_item_id", "count"),
        product_value=("price", "sum"),
        freight_value=("freight_value", "sum")
    )
    .reset_index()
)


order_item_summary["order_value"] = (
    order_item_summary["product_value"]
    + order_item_summary["freight_value"]
)

# Merge orders + reviews
order_analysis = delivered_orders.merge(
    reviews[
        [
            "order_id",
            "review_score",
            "is_negative_review",
            "is_one_star"
        ]
    ],
    on="order_id",
    how="left"
)

# Merge order value
order_analysis = order_analysis.merge(
    order_item_summary,
    on="order_id",
    how="left"
)

# Merge customer data
customer_columns = [
    "customer_id",
    "customer_unique_id",
    "customer_zip_code_prefix",
    "customer_city",
    "customer_state"
]

customer_columns = [
    col for col in customer_columns
    if col in customers.columns
]


order_analysis = order_analysis.merge(
    customers[customer_columns],
    on="customer_id",
    how="left"
)


print("=" * 80)
print("ORDER ANALYSIS")
print("=" * 80)

print("Shape:", order_analysis.shape)

print("\nColumns:")
print(order_analysis.columns.tolist())

print("\nFirst rows:")
display(order_analysis.head())

"""###9. DELIVERY VS CUSTOMER SATISFACTION"""

delivery_satisfaction = (
    order_analysis
    .groupby("is_late")
    .agg(
        orders=("order_id", "nunique"),
        average_rating=("review_score", "mean"),
        negative_review_rate=("is_negative_review", "mean"),
        one_star_rate=("is_one_star", "mean")
    )
    .reset_index()
)


delivery_satisfaction["delivery_status"] = (
    delivery_satisfaction["is_late"]
    .map({
        0: "On Time",
        1: "Late"
    })
)


delivery_satisfaction["negative_review_rate"] *= 100
delivery_satisfaction["one_star_rate"] *= 100


print("=" * 80)
print("DELIVERY VS CUSTOMER SATISFACTION")
print("=" * 80)

display(delivery_satisfaction)

# Visualization
plt.figure(figsize=(8, 5))

sns.barplot(
    data=delivery_satisfaction,
    x="delivery_status",
    y="average_rating"
)

plt.title(
    "Average Customer Rating: On-Time vs Late Delivery"
)

plt.xlabel("Delivery Status")
plt.ylabel("Average Review Score")

plt.ylim(0, 5)

plt.tight_layout()
plt.show()

# Delay vs rating
delay_rating = (
    order_analysis
    .groupby("review_score")
    .agg(
        average_delay=("delivery_delay_days", "mean"),
        median_delay=("delivery_delay_days", "median"),
        orders=("order_id", "nunique")
    )
    .reset_index()
)


display(delay_rating)


plt.figure(figsize=(9, 5))

sns.barplot(
    data=delay_rating,
    x="review_score",
    y="average_delay"
)

plt.title(
    "Average Delivery Delay by Customer Rating"
)

plt.xlabel("Review Score")
plt.ylabel("Average Delay (Days)")

plt.tight_layout()
plt.show()

"""###10. PRODUCT AND CATEGORY ANALYSIS"""

# Create item-level dataset
item_analysis = order_items.merge(
    products,
    on="product_id",
    how="left"
)


item_analysis = item_analysis.merge(
    sellers,
    on="seller_id",
    how="left"
)

# Category column
if "product_category_name_english" not in item_analysis.columns:

    if "product_category_name" in item_analysis.columns:

        item_analysis["product_category_name_english"] = (
            item_analysis["product_category_name"]
        )


item_analysis["product_category_name_english"] = (
    item_analysis["product_category_name_english"]
    .fillna("unknown")
)

# Category sales
category_performance = (
    item_analysis
    .groupby("product_category_name_english")
    .agg(
        orders=("order_id", "nunique"),
        items=("order_item_id", "count"),
        revenue=("price", "sum"),
        freight=("freight_value", "sum")
    )
    .reset_index()
    .sort_values("revenue", ascending=False)
)


print("=" * 80)
print("TOP PRODUCT CATEGORIES")
print("=" * 80)

display(category_performance.head(20))

# Category reviews
category_reviews = item_analysis[
    [
        "order_id",
        "product_category_name_english",
        "seller_id"
    ]
].merge(
    reviews[
        [
            "order_id",
            "review_score",
            "is_negative_review",
            "is_one_star"
        ]
    ],
    on="order_id",
    how="left"
)

# Category satisfaction
category_satisfaction = (
    category_reviews
    .groupby("product_category_name_english")
    .agg(
        orders=("order_id", "nunique"),
        average_rating=("review_score", "mean"),
        negative_rate=("is_negative_review", "mean"),
        one_star_rate=("is_one_star", "mean")
    )
    .reset_index()
)


category_satisfaction["negative_rate"] *= 100
category_satisfaction["one_star_rate"] *= 100

# Remove small categories
category_satisfaction_filtered = (
    category_satisfaction[
        category_satisfaction["orders"] >= 100
    ]
    .copy()
)


print("=" * 80)
print("LOWEST-RATED CATEGORIES")
print("=" * 80)

display(
    category_satisfaction_filtered
    .sort_values("average_rating")
    .head(15)
)


print("=" * 80)
print("HIGHEST ONE-STAR RATE CATEGORIES")
print("=" * 80)

display(
    category_satisfaction_filtered
    .sort_values(
        "one_star_rate",
        ascending=False
    )
    .head(15)
)

# Visualization
top_bad_categories = (
    category_satisfaction_filtered
    .sort_values("average_rating")
    .head(15)
)


plt.figure(figsize=(10, 7))

sns.barplot(
    data=top_bad_categories,
    y="product_category_name_english",
    x="average_rating"
)

plt.title("Lowest-Rated Product Categories")

plt.xlabel("Average Review Score")
plt.ylabel("Product Category")

plt.xlim(0, 5)

plt.tight_layout()
plt.show()

"""###11. SELLER AND REGIONAL ANALYSIS"""

# SELLER SATISFACTION
seller_performance = (
    category_reviews
    .groupby("seller_id")
    .agg(
        orders=("order_id", "nunique"),
        average_rating=("review_score", "mean"),
        negative_rate=("is_negative_review", "mean"),
        one_star_rate=("is_one_star", "mean")
    )
    .reset_index()
)


seller_performance["negative_rate"] *= 100
seller_performance["one_star_rate"] *= 100


seller_performance_filtered = (
    seller_performance[
        seller_performance["orders"] >= 50
    ]
    .copy()
)

# SELLER DELIVERY PERFORMANCE
seller_order_list = (
    item_analysis[
        [
            "order_id",
            "seller_id"
        ]
    ]
    .drop_duplicates()
)


seller_delivery = seller_order_list.merge(
    delivered_orders[
        [
            "order_id",
            "delivery_days",
            "delivery_delay_days",
            "is_late"
        ]
    ],
    on="order_id",
    how="inner"
)


seller_delivery_summary = (
    seller_delivery
    .groupby("seller_id")
    .agg(
        delivery_orders=("order_id", "nunique"),
        avg_delivery_days=("delivery_days", "mean"),
        avg_delay_days=("delivery_delay_days", "mean"),
        late_rate=("is_late", "mean")
    )
    .reset_index()
)


seller_delivery_summary["late_rate"] *= 100

# FINAL SELLER PERFORMANCE
seller_performance_final = (
    seller_performance_filtered
    .merge(
        seller_delivery_summary,
        on="seller_id",
        how="left"
    )
)

# HIGH-RISK SELLERS
high_risk_sellers = seller_performance_final[
    (seller_performance_final["orders"] >= 100) &
    (seller_performance_final["average_rating"] < 3.5) &
    (seller_performance_final["late_rate"] > 20)
].copy()


print("=" * 80)
print("HIGH-RISK SELLERS")
print("=" * 80)

display(
    high_risk_sellers
    .sort_values(
        ["late_rate", "average_rating"],
        ascending=[False, True]
    )
    .head(20)
)

# REGIONAL PERFORMANCE
regional_performance = (
    order_analysis
    .groupby("customer_state")
    .agg(
        orders=("order_id", "nunique"),
        revenue=("order_value", "sum"),
        average_rating=("review_score", "mean"),
        negative_rate=("is_negative_review", "mean"),
        late_rate=("is_late", "mean"),
        average_delivery_days=("delivery_days", "mean")
    )
    .reset_index()
)


regional_performance["negative_rate"] *= 100
regional_performance["late_rate"] *= 100


print("=" * 80)
print("REGIONS WITH HIGHEST LATE DELIVERY")
print("=" * 80)

display(
    regional_performance
    .sort_values(
        "late_rate",
        ascending=False
    )
)

# REGIONAL VISUALIZATION
top_late_regions = (
    regional_performance
    .sort_values(
        "late_rate",
        ascending=False
    )
    .head(15)
)


plt.figure(figsize=(10, 7))

sns.barplot(
    data=top_late_regions,
    y="customer_state",
    x="late_rate"
)

plt.title("States with Highest Late Delivery Rate")

plt.xlabel("Late Delivery Rate (%)")
plt.ylabel("State")

plt.tight_layout()
plt.show()

"""###12. ADDITIONAL ANALYSIS AND VISUALIZATIONS"""

# FREIGHT COST VS RATING
freight_analysis = (
    order_analysis
    .groupby("review_score")
    .agg(
        orders=("order_id", "nunique"),
        average_freight=("freight_value", "mean"),
        average_order_value=("order_value", "mean"),
        average_delivery_days=("delivery_days", "mean")
    )
    .reset_index()
)


print("=" * 80)
print("FREIGHT COST VS CUSTOMER RATING")
print("=" * 80)

display(freight_analysis)


plt.figure(figsize=(9, 5))

sns.barplot(
    data=freight_analysis,
    x="review_score",
    y="average_freight"
)

plt.title("Average Freight Cost by Customer Rating")

plt.xlabel("Review Score")
plt.ylabel("Average Freight Value")

plt.tight_layout()
plt.show()

# CATEGORY SALES + SATISFACTION
category_final = category_performance.merge(
    category_satisfaction,
    on="product_category_name_english",
    how="left",
    suffixes=("_sales", "_satisfaction")
)


category_matrix = (
    category_final[
        category_final["orders_sales"] >= 100
    ]
    .copy()
)

# STRATEGIC CATEGORY CLASSIFICATION
revenue_median = category_matrix["revenue"].median()
rating_median = category_matrix["average_rating"].median()


def classify_category(row):

    high_revenue = row["revenue"] >= revenue_median
    high_satisfaction = row["average_rating"] >= rating_median

    if high_revenue and high_satisfaction:
        return "Invest"

    elif high_revenue and not high_satisfaction:
        return "Intervene"

    elif not high_revenue and high_satisfaction:
        return "Maintain"

    else:
        return "Review"


category_matrix["strategy"] = (
    category_matrix
    .apply(classify_category, axis=1)
)


strategic_columns = [
    "product_category_name_english",
    "revenue",
    "orders_sales",
    "average_rating",
    "negative_rate",
    "one_star_rate",
    "strategy"
]


print("=" * 80)
print("CATEGORY STRATEGY")
print("=" * 80)

display(
    category_matrix[
        strategic_columns
    ]
    .sort_values("revenue", ascending=False)
)

# GROWTH VS SATISFACTION
plt.figure(figsize=(11, 7))

sns.scatterplot(
    data=category_matrix,
    x="revenue",
    y="average_rating",
    size="orders_sales",
    hue="strategy",
    sizes=(50, 500),
    alpha=0.7
)

plt.axhline(
    rating_median,
    linestyle="--"
)

plt.axvline(
    revenue_median,
    linestyle="--"
)

plt.title("Category Revenue vs Customer Satisfaction")

plt.xlabel("Revenue")
plt.ylabel("Average Review Score")

plt.tight_layout()
plt.show()

# REVIEW SCORE DISTRIBUTION
plt.figure(figsize=(8, 5))

sns.countplot(
    data=reviews,
    x="review_score"
)

plt.title("Distribution of Customer Review Scores")

plt.xlabel("Review Score")
plt.ylabel("Number of Reviews")

plt.tight_layout()
plt.show()

# ORDER VALUE DISTRIBUTION
plt.figure(figsize=(9, 5))

sns.histplot(
    order_analysis["order_value"].dropna(),
    bins=50
)

plt.title("Distribution of Order Value")

plt.xlabel("Order Value")
plt.ylabel("Number of Orders")

plt.tight_layout()
plt.show()

# DELIVERY TIME DISTRIBUTION
plt.figure(figsize=(9, 5))

sns.histplot(
    delivered_orders["delivery_days"].dropna(),
    bins=50
)

plt.title("Distribution of Delivery Time")

plt.xlabel("Delivery Time (Days)")
plt.ylabel("Number of Orders")

plt.tight_layout()
plt.show()

# DELIVERY PERFORMANCE DISTRIBUTION
delivery_counts = (
    delivered_orders["delivery_performance"]
    .value_counts()
)


plt.figure(figsize=(9, 5))

sns.barplot(
    x=delivery_counts.index,
    y=delivery_counts.values
)

plt.title("Delivery Performance Distribution")

plt.xlabel("Delivery Performance")
plt.ylabel("Number of Orders")

plt.xticks(rotation=20)

plt.tight_layout()
plt.show()

"""###13. SAVE ANALYTICAL DATASETS"""

order_analysis.to_csv(
    f"{OUTPUT_PATH}/order_analysis.csv",
    index=False
)

category_final.to_csv(
    f"{OUTPUT_PATH}/category_performance.csv",
    index=False
)

seller_performance_final.to_csv(
    f"{OUTPUT_PATH}/seller_performance.csv",
    index=False
)

regional_performance.to_csv(
    f"{OUTPUT_PATH}/regional_performance.csv",
    index=False
)

delivery_satisfaction.to_csv(
    f"{OUTPUT_PATH}/delivery_satisfaction.csv",
    index=False
)

category_matrix.to_csv(
    f"{OUTPUT_PATH}/category_strategy.csv",
    index=False
)

delivered_orders.to_csv(
    f"{OUTPUT_PATH}/delivered_orders.csv",
    index=False
)

item_analysis.to_csv(
    f"{OUTPUT_PATH}/item_analysis.csv",
    index=False
)


print("=" * 80)
print("ANALYTICAL DATASETS SAVED")
print("=" * 80)

print("\nOutput directory:")
print(OUTPUT_PATH)

print("\nFiles created:")

print("1. order_analysis.csv")
print("2. category_performance.csv")
print("3. seller_performance.csv")
print("4. regional_performance.csv")
print("5. delivery_satisfaction.csv")
print("6. category_strategy.csv")
print("7. delivered_orders.csv")
print("8. item_analysis.csv")

"""###14. FINAL BUSINESS METRICS"""

print("=" * 80)
print("KEY BUSINESS METRICS")
print("=" * 80)

print(
    f"Total orders: "
    f"{orders['order_id'].nunique():,}"
)

print(
    f"Delivered orders: "
    f"{delivered_orders['order_id'].nunique():,}"
)

print(
    f"Customers: "
    f"{customers['customer_unique_id'].nunique():,}"
)

print(
    f"Sellers: "
    f"{sellers['seller_id'].nunique():,}"
)

print(
    f"Average rating: "
    f"{reviews['review_score'].mean():.2f} / 5"
)

print(
    f"Late delivery rate: "
    f"{late_rate:.2f}%"
)

print(
    f"Negative review rate: "
    f"{reviews['is_negative_review'].mean() * 100:.2f}%"
)

print(
    f"One-star review rate: "
    f"{reviews['is_one_star'].mean() * 100:.2f}%"
)

print("\n")
print("=" * 80)
print("ANALYSIS COMPLETE")
print("=" * 80)

import shutil
from google.colab import files

shutil.make_archive(
    "/content/analysis_output",
    "zip",
    "/content/analysis_output"
)

files.download("/content/analysis_output.zip")



import pandas as pd
import os

folder = "/content/analysis_output"

for file in sorted(os.listdir(folder)):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(folder, file))

        print(f"\n{'='*80}")
        print(f"{file}  |  Shape: {df.shape}")
        print(f"{'='*80}")
        print(", ".join(df.columns.tolist()))